### ISSUE TITLE
有内核版本的限制么？

### ISSUE THREAD

**Issue by spyman1802** [lisaac/tproxy-gateway#4]
因为我不用IPv6，所以，我在centos7.4的kernel的启动参数上，禁止了IPV6. 以下的错误，不知道是不是因为这个引起的。 
May 20 23:52:38 localhost kernel: docker0: port 2(veth1d57d8b) entered disabled state
May 20 23:52:38 localhost kernel: device veth1d57d8b left promiscuous mode
我上网查询了这个问题，发现一个https://www.v2ex.com/amp/t/370924帖子说，这个是内核的bug。
我现在用docker启动，作为网管以后，效果特别差， 经常不能正常使用网络。注意，是不能正常使用网络，不是翻墙。我连访问国内网络也会有问题。
不知道，你那边做的测试，用的是那个操作系统，那一个版本？

**Comment by lisaac** [comment]
没有碰到过类似情况，用的是debian testing
内核4.19
不清楚是否和禁用ipv6有关，如果禁用了，需要把ipv6相关参数去掉。

spyman1802 <notifications@github.com> 于 2019年5月20日周一 23:56写道：
